/**
 * Shared email sending utility for scout workflow emails.
 */

export async function sendNotificationEmailHelper(opts: {
  to: string;
  subject: string;
  html: string;
  notificationId: string;
}): Promise<boolean> {
  try {
    const appHostname = (process.env.NEXTAUTH_URL || '').replace(/^https?:\/\//, '').split('/')[0];
    const res = await fetch('https://apps.abacus.ai/api/sendNotificationEmail', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        deployment_token: process.env.ABACUSAI_API_KEY,
        app_id: process.env.WEB_APP_ID,
        notification_id: opts.notificationId,
        subject: opts.subject,
        body: opts.html,
        is_html: true,
        recipient_email: opts.to,
        sender_email: `noreply@${appHostname}`,
        sender_alias: 'Ad Launch',
      }),
    });
    const data = await res.json().catch(() => ({}));
    if (!data?.success) {
      console.error('[scout-email] Send failed:', JSON.stringify(data));
      return false;
    }
    return true;
  } catch (err: any) {
    console.error('[scout-email] Send error:', err?.message);
    return false;
  }
}

export function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/** Build post-ready completion email HTML */
export function buildCompletionEmailHtml(opts: {
  businessName: string;
  storyTitle: string;
  storySource: string;
  postCopy: string;
  headline: string;
  imageUrl: string;
  reviewUrl: string;
  downloadUrl: string;
}): string {
  const imgBlock = opts.imageUrl ? `
    <div style="text-align: center; margin: 16px 0;">
      <img src="${opts.imageUrl}" alt="Post preview" style="max-width: 100%; border-radius: 8px; border: 1px solid #e2e8f0;" />
    </div>` : '';

  return `
    <div style="max-width: 600px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #ffffff;">
      <div style="background: #059669; color: white; padding: 24px; text-align: center; border-radius: 12px 12px 0 0;">
        <h1 style="margin: 0; font-size: 20px; font-weight: 700;">✅ Your Ad Launch Post is Ready</h1>
        <p style="margin: 8px 0 0 0; font-size: 14px; color: #d1fae5;">for ${escHtml(opts.businessName)}</p>
      </div>

      <div style="padding: 24px;">
        <div style="background: #f8fafc; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
          <div style="font-size: 12px; color: #64748b; margin-bottom: 4px;">Based on: ${escHtml(opts.storySource)}</div>
          <div style="font-weight: 600; color: #1e293b; font-size: 15px; margin-bottom: 8px;">${escHtml(opts.storyTitle)}</div>
          ${opts.headline ? `<div style="font-size: 14px; font-weight: 600; color: #2563eb; margin-bottom: 4px;">${escHtml(opts.headline)}</div>` : ''}
          <div style="font-size: 13px; color: #475569; white-space: pre-line;">${escHtml(opts.postCopy).slice(0, 300)}${opts.postCopy.length > 300 ? '...' : ''}</div>
        </div>

        ${imgBlock}

        <div style="text-align: center; margin-top: 24px;">
          <a href="${opts.reviewUrl}" style="display: inline-block; background: #2563eb; color: white; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 14px; margin-right: 8px;">Review & Download</a>
        </div>
        <div style="text-align: center; margin-top: 12px;">
          <a href="${opts.downloadUrl}" style="display: inline-block; background: #0f172a; color: white; padding: 10px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 13px;">Download Package</a>
        </div>

        <p style="font-size: 11px; color: #94a3b8; text-align: center; margin-top: 20px;">
          This post was generated by Ad Launch. Review and post manually to your social accounts.
        </p>
      </div>
    </div>
  `;
}
