/**
 * National RSS Feed Discovery Seed Script
 * Seeds validated, brand-safe national RSS feeds across 10 industries.
 * 
 * Run: cd nextjs_space && npx ts-node scripts/seed-national-feeds.ts
 * Or:  cd nextjs_space && npx tsx scripts/seed-national-feeds.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface FeedSeed {
  url: string;
  title: string;
  description: string;
  siteUrl: string;
  industry: string;
  sourceType: string;
  sourceQuality: string;
  contentTags: string[];
  qualityScore: number;
  localizable: boolean;
  updateFrequency: string;
  notes: string;
}

const NATIONAL_FEEDS: FeedSeed[] = [
  // ═══════════════════════════════════════════════════════════════
  // TECHNOLOGY (consumer tech, IT support)
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.theverge.com/rss/index.xml',
    title: 'The Verge',
    description: 'Covers the intersection of technology, science, art, and culture with in-depth reporting and product information.',
    siteUrl: 'https://www.theverge.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Top-tier consumer tech publication. Great for "Did you know?" and "This week in tech" posts.',
  },
  {
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    title: 'Ars Technica',
    description: 'In-depth technology news, analysis, and reviews for tech-savvy readers.',
    siteUrl: 'https://arstechnica.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'how-to', 'tips'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Highly credible tech journalism. Deep dives on consumer tech and science.',
  },
  {
    url: 'https://www.engadget.com/rss.xml',
    title: 'Engadget',
    description: 'Technology news, reviews, and analysis of the latest gadgets and consumer electronics.',
    siteUrl: 'https://www.engadget.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'alerts'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Strong gadget and consumer electronics focus. Good for product-related social posts.',
  },
  {
    url: 'https://www.techradar.com/rss',
    title: 'TechRadar',
    description: 'Latest technology news, reviews, computing, phones, home entertainment, and gadgets.',
    siteUrl: 'https://www.techradar.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Broad tech coverage. Excellent buying guides and how-to content.',
  },
  {
    url: 'https://www.zdnet.com/news/rss.xml',
    title: 'ZDNet',
    description: 'Technology news for IT professionals covering enterprise tech, security, and emerging trends.',
    siteUrl: 'https://www.zdnet.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Enterprise + consumer tech. Good for B2B-facing businesses.',
  },
  {
    url: 'https://www.howtogeek.com/feed/',
    title: 'How-To Geek',
    description: 'Technology tutorials, tips, and how-to guides for everyday tech problems.',
    siteUrl: 'https://www.howtogeek.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Perfect for "Did you know?" and "Tips" social posts. Highly actionable content.',
  },
  {
    url: 'https://www.makeuseof.com/feed/',
    title: 'MakeUseOf',
    description: 'Technology guides, tips, and tutorials helping users get the most from their devices.',
    siteUrl: 'https://www.makeuseof.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Practical tech tips and tutorials. Great for repurposing into social tips.',
  },
  {
    url: 'https://www.digitaltrends.com/feed/',
    title: 'Digital Trends',
    description: 'Expert reviews, news, buying guides, deals, and how-to insights on consumer tech.',
    siteUrl: 'https://www.digitaltrends.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Strong consumer tech reviews and deals coverage.',
  },
  {
    url: 'https://venturebeat.com/feed/',
    title: 'VentureBeat',
    description: 'Transformative tech news covering AI, machine learning, and the game industry.',
    siteUrl: 'https://venturebeat.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: false,
    updateFrequency: 'multiple_daily',
    notes: 'AI and enterprise tech focus. Good for "This week in AI" posts.',
  },
  {
    url: 'https://www.pcworld.com/feed',
    title: 'PCWorld',
    description: 'PC hardware reviews, Windows tips, buying guides, and tech news.',
    siteUrl: 'https://www.pcworld.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'PC-focused. Great for IT support businesses.',
  },
  {
    url: 'https://www.computerworld.com/feed',
    title: 'Computerworld',
    description: 'Technology topics including software, security, operating systems, mobile, and emerging tech.',
    siteUrl: 'https://www.computerworld.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Enterprise IT focus. Good for MSP and IT support businesses.',
  },
  {
    url: 'https://www.geekwire.com/feed/',
    title: 'GeekWire',
    description: 'Tech news from Seattle covering startups, innovation, and the tech industry.',
    siteUrl: 'https://www.geekwire.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Regional tech news with national relevance. Startup and innovation stories.',
  },
  {
    url: 'https://spectrum.ieee.org/feeds/feed.rss',
    title: 'IEEE Spectrum',
    description: 'Technology news and analysis from the world\'s leading engineering magazine.',
    siteUrl: 'https://spectrum.ieee.org',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'official',
    contentTags: ['news', 'did-you-know', 'how-to'],
    qualityScore: 9,
    localizable: false,
    updateFrequency: 'daily',
    notes: 'Authoritative engineering publication. Excellent for educational content.',
  },
  {
    url: 'https://slashdot.org/rss/slashdot.rss',
    title: 'Slashdot',
    description: 'News for nerds — technology news and discussion community.',
    siteUrl: 'https://slashdot.org',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'multiple_daily',
    notes: 'Community-driven tech news aggregator. Good for trending tech topics.',
  },
  {
    url: 'https://mashable.com/feeds/rss/all',
    title: 'Mashable',
    description: 'Digital culture, entertainment, and innovative tech for the connected generation.',
    siteUrl: 'https://mashable.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Digital lifestyle and tech culture. Great for social media-friendly content.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE (maintenance, repair, recalls, trends)
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.caranddriver.com/rss/all.xml/',
    title: 'Car and Driver',
    description: 'Expert car reviews, news, buying guides, and automotive journalism.',
    siteUrl: 'https://www.caranddriver.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Top-tier automotive journalism. Great for "This week in auto" posts.',
  },
  {
    url: 'https://www.edmunds.com/feeds/rss/articles.xml',
    title: 'Edmunds',
    description: 'Car buying advice, reviews, pricing, and automotive research tools.',
    siteUrl: 'https://www.edmunds.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Authoritative buying guides. Perfect for auto dealerships and repair shops.',
  },
  {
    url: 'https://www.thedrive.com/feed',
    title: 'The Drive',
    description: 'Automotive news, car reviews, how-tos, and buying guides.',
    siteUrl: 'https://www.thedrive.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'how-to', 'tips'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Modern automotive journalism with strong how-to section.',
  },
  {
    url: 'https://www.torquenews.com/rss.xml',
    title: 'Torque News',
    description: 'Automotive news covering new models, recalls, EV trends, and industry updates.',
    siteUrl: 'https://www.torquenews.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Strong recall and safety alert coverage. Good for "Alert" posts.',
  },
  {
    url: 'https://www.kbb.com/rss/',
    title: 'Kelley Blue Book',
    description: 'Car pricing, reviews, and buying guides from the most trusted name in auto valuation.',
    siteUrl: 'https://www.kbb.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'official',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Industry standard for pricing. Great for "Did you know?" about car values.',
  },
  {
    url: 'https://jalopnik.com/rss',
    title: 'Jalopnik',
    description: 'Car culture, news, reviews, and automotive stories.',
    siteUrl: 'https://jalopnik.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Engaging car culture content. Good for fun automotive social posts.',
  },
  {
    url: 'https://www.carcomplaints.com/news/feed.xml',
    title: 'CarComplaints',
    description: 'Vehicle recalls, complaints, and technical service bulletins.',
    siteUrl: 'https://www.carcomplaints.com',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['alerts', 'news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Critical recall and safety info. Perfect for "Alert" posts for auto shops.',
  },
  {
    url: 'https://feeds.feedburner.com/1aAutoBlog',
    title: '1A Auto Blog',
    description: 'Automotive DIY repair guides, how-to videos, and car maintenance tips.',
    siteUrl: 'https://www.1aauto.com/blog',
    industry: 'automotive',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Excellent DIY content. Perfect for auto repair shops to share maintenance tips.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RURAL LIVING / AGRICULTURE / HOMESTEADING
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://modernfarmer.com/feed/',
    title: 'Modern Farmer',
    description: 'Food, lifestyle, and agriculture stories connecting farms to the broader culture.',
    siteUrl: 'https://modernfarmer.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Premium agricultural storytelling. Great for rural businesses.',
  },
  {
    url: 'https://agdaily.com/feed/',
    title: 'AGDAILY',
    description: 'Production farming news, rural living, agriculture trends, and rural lifestyle.',
    siteUrl: 'https://agdaily.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Covers both production agriculture and rural lifestyle.',
  },
  {
    url: 'https://www.hobbyfarms.com/feed/',
    title: 'Hobby Farms',
    description: 'Rural living for pleasure and profit — growing food, raising animals, and farm life.',
    siteUrl: 'https://www.hobbyfarms.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Perfect for small farm and rural lifestyle audiences.',
  },
  {
    url: 'https://brownfieldagnews.com/feed/',
    title: 'Brownfield Ag News',
    description: 'Agricultural news, market reports, weather, and features for U.S. farms and rural communities.',
    siteUrl: 'https://brownfieldagnews.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Comprehensive U.S. ag news with market data.',
  },
  {
    url: 'https://www.farmprogress.com/rss.xml',
    title: 'Farm Progress',
    description: 'Agriculture industry news, crop management, livestock, and farm technology.',
    siteUrl: 'https://www.farmprogress.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'alerts'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Major ag industry publication covering crop and livestock management.',
  },
  {
    url: 'https://smallfarmersjournal.com/feed/',
    title: 'Small Farmer\'s Journal',
    description: 'Practical wisdom for independent family farms and sustainable agriculture.',
    siteUrl: 'https://smallfarmersjournal.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Niche family farm content. Authentic rural voice.',
  },
  {
    url: 'https://commonsensehome.com/feed/',
    title: 'Common Sense Home',
    description: 'Self-reliance tips — gardening, food storage, preparedness, home remedies, and herbalism.',
    siteUrl: 'https://commonsensehome.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Homesteading and self-sufficiency. Great for feed stores and rural retailers.',
  },
  {
    url: 'https://practicalselfreliance.com/feed/',
    title: 'Practical Self Reliance',
    description: 'Practical ways to become more self-reliant — off-grid homesteading, gardening, and food preservation.',
    siteUrl: 'https://practicalselfreliance.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Off-grid and homesteading content. Strong DIY focus.',
  },
  {
    url: 'https://ruralsprout.com/feed/',
    title: 'Rural Sprout',
    description: 'Expert advice on growing food, homesteading, and creating a natural home.',
    siteUrl: 'https://ruralsprout.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Homesteading and gardening tips with beautiful photography.',
  },
  {
    url: 'https://homesteadingfamily.com/feed/',
    title: 'Homesteading Family',
    description: 'Education on growing, preserving, and thriving on a homestead.',
    siteUrl: 'https://homesteadingfamily.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Family-friendly homesteading education. Great for rural community posts.',
  },
  {
    url: 'https://melissaknorris.com/feed/',
    title: 'Melissa K. Norris - Pioneering Today',
    description: 'Food preservation, homestead life, gardening, natural medicine, and raising food.',
    siteUrl: 'https://melissaknorris.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Pioneering/homestead lifestyle with practical food preservation guides.',
  },
  {
    url: 'https://littlehouseliving.com/feed/',
    title: 'Little House Living',
    description: 'Simple living ideas, frugal tips, modern homesteading, recipes, and gardening.',
    siteUrl: 'https://littlehouseliving.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 6,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Frugal living and simple homesteading. Good for rural audience engagement.',
  },
  {
    url: 'https://thriftyhomesteader.com/feed/',
    title: 'The Thrifty Homesteader',
    description: 'Living a cheaper, greener, healthier life — gardening, cooking, raising chickens and goats.',
    siteUrl: 'https://thriftyhomesteader.com',
    industry: 'rural_agriculture',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['how-to', 'tips'],
    qualityScore: 6,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Budget-conscious homesteading. Good for feed stores and farm supply shops.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RODEO / WESTERN LIFESTYLE
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.thecowboychannel.com/rodeo.rss',
    title: 'The Cowboy Channel — Rodeo',
    description: 'Professional rodeo news, event coverage, athlete profiles, and Western sports.',
    siteUrl: 'https://www.thecowboychannel.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Primary source for professional rodeo coverage.',
  },
  {
    url: 'https://wpra.com/feed/',
    title: 'Women\'s Professional Rodeo Association',
    description: 'WPRA news, barrel racing, team roping, standings, and schedule updates.',
    siteUrl: 'https://wpra.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'official',
    contentTags: ['news', 'alerts'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Official WPRA source. Great for barrel racing and women\'s rodeo content.',
  },
  {
    url: 'https://cowgirlmagazine.com/feed/',
    title: 'COWGIRL Magazine',
    description: 'Western lifestyle for women — horses, fashion, rodeo, home, travel, and culture.',
    siteUrl: 'https://cowgirlmagazine.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Western lifestyle and rodeo for women. Great for Western retail and ranching.',
  },
  {
    url: 'https://westernlifetoday.com/feed/',
    title: 'Western Life Today',
    description: 'Modern Western fashion, entertainment, destinations, and cowboy/cowgirl culture.',
    siteUrl: 'https://westernlifetoday.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Western lifestyle and culture publication.',
  },
  {
    url: 'https://americancowboy.com/feed/',
    title: 'American Cowboy',
    description: 'Cowboy and cowgirl lifestyle — ranching, rodeo, Western news, people, and travel.',
    siteUrl: 'https://americancowboy.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Authentic American cowboy culture and lifestyle.',
  },
  {
    url: 'https://thesouthdakotacowgirl.com/feed/',
    title: 'The South Dakota Cowgirl',
    description: 'Life on the ranch — horses, cattle, dogs, equipment, and Western traditions.',
    siteUrl: 'https://thesouthdakotacowgirl.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['did-you-know', 'tips'],
    qualityScore: 6,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Authentic ranch life content from a working ranch perspective.',
  },
  {
    url: 'https://thenativecowgirl.com/blog-feed.xml',
    title: 'The Native Cowgirl',
    description: 'Ranching, rodeo, and rural entrepreneurship — empowering women in agriculture.',
    siteUrl: 'https://thenativecowgirl.com',
    industry: 'rodeo_western',
    sourceType: 'national_news',
    sourceQuality: 'community',
    contentTags: ['did-you-know', 'tips', 'how-to'],
    qualityScore: 6,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Women in agriculture and rural entrepreneurship.',
  },

  // ═══════════════════════════════════════════════════════════════
  // SMALL BUSINESS / ENTREPRENEURSHIP
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.entrepreneur.com/latest.rss',
    title: 'Entrepreneur',
    description: 'Business news, startup advice, growth strategies, and entrepreneurship solutions.',
    siteUrl: 'https://www.entrepreneur.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Premier entrepreneurship publication. Great for any business audience.',
  },
  {
    url: 'https://feeds.feedburner.com/SmallBusinessTrends',
    title: 'Small Business Trends',
    description: 'News, tips, advice, and resources for small businesses covering marketing, management, and tech.',
    siteUrl: 'https://smallbiztrends.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Award-winning small business resource. Perfect for B2B social content.',
  },
  {
    url: 'https://www.inc.com/rss',
    title: 'Inc.',
    description: 'Ideas, resources, advice, and strategies for starting and growing a business.',
    siteUrl: 'https://www.inc.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Top business publication. Excellent for thought leadership content.',
  },
  {
    url: 'https://www.fastcompany.com/latest/rss?truncated=true',
    title: 'Fast Company',
    description: 'Innovation in technology, leadership, and design for forward-thinking businesses.',
    siteUrl: 'https://www.fastcompany.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Innovation and design focus. Great for creative and tech businesses.',
  },
  {
    url: 'https://www.uschamber.com/co/feeds/rss',
    title: 'CO— by U.S. Chamber of Commerce',
    description: 'Small business resources — starting, running, growing, and marketing a business.',
    siteUrl: 'https://www.uschamber.com/co',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'official',
    contentTags: ['tips', 'how-to', 'news'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Official U.S. Chamber resource. Highly credible for business owners.',
  },
  {
    url: 'https://foundr.com/articles/feed',
    title: 'Foundr',
    description: 'Entrepreneurship education — lessons from leading founders in content, podcast, and courses.',
    siteUrl: 'https://foundr.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Startup founder stories and lessons. Good for motivational business content.',
  },
  {
    url: 'https://www.ducttapemarketing.com/feed/',
    title: 'Duct Tape Marketing',
    description: 'Small business marketing ideas, tips, guides on advertising, SEO, and social media.',
    siteUrl: 'https://www.ducttapemarketing.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Marketing-focused small business advice. Great for marketing agencies.',
  },
  {
    url: 'https://succeedasyourownboss.com/feed/',
    title: 'Succeed As Your Own Boss (SmallBizLady)',
    description: 'Small business expert advice on growth, branding, marketing, and customer service.',
    siteUrl: 'https://succeedasyourownboss.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'America\'s #1 Small Business Expert. Practical growth advice.',
  },
  {
    url: 'https://crowdspring.com/blog/feed/',
    title: 'Crowdspring Blog',
    description: 'Marketing, startups, small business, and design tips for entrepreneurs.',
    siteUrl: 'https://crowdspring.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Design and branding tips for small businesses.',
  },
  {
    url: 'https://tim.blog/feed/',
    title: 'Tim Ferriss Blog',
    description: 'Productivity, business, and lifestyle optimization from bestselling author Tim Ferriss.',
    siteUrl: 'https://tim.blog',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'did-you-know'],
    qualityScore: 8,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Influential business/productivity blog. Great for motivational posts.',
  },
  {
    url: 'https://blog.hubspot.com/marketing/rss.xml',
    title: 'HubSpot Marketing Blog',
    description: 'Marketing tips, trends, and strategies for growing businesses.',
    siteUrl: 'https://blog.hubspot.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Industry-leading marketing education. Great for marketing-related businesses.',
  },
  {
    url: 'https://www.socialmediaexaminer.com/feed/',
    title: 'Social Media Examiner',
    description: 'Social media marketing tips, strategies, and platform updates for businesses.',
    siteUrl: 'https://www.socialmediaexaminer.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'news'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Top social media marketing resource. Perfect for businesses managing social accounts.',
  },
  {
    url: 'https://copyblogger.com/feed/',
    title: 'Copyblogger',
    description: 'Content marketing, copywriting, and SEO strategies for online businesses.',
    siteUrl: 'https://copyblogger.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Copywriting and content marketing authority.',
  },
  {
    url: 'https://neilpatel.com/feed/',
    title: 'Neil Patel Blog',
    description: 'Digital marketing, SEO, and growth strategies for online businesses.',
    siteUrl: 'https://neilpatel.com',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'SEO and digital marketing expertise. Good for business growth tips.',
  },
  {
    url: 'https://buffer.com/resources/feed/',
    title: 'Buffer Blog',
    description: 'Social media marketing strategies, tips, and platform insights.',
    siteUrl: 'https://buffer.com/resources',
    industry: 'small_business',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 7,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Social media scheduling platform blog. Practical social media tips.',
  },

  // ═══════════════════════════════════════════════════════════════
  // WEATHER / ALERTS
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.weather.gov/rss_page.php?site_name=nws',
    title: 'National Weather Service — Headlines',
    description: 'Official NWS weather headlines, alerts, and advisories for the United States.',
    siteUrl: 'https://www.weather.gov',
    industry: 'weather',
    sourceType: 'weather',
    sourceQuality: 'official',
    contentTags: ['alerts', 'news'],
    qualityScore: 10,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Official U.S. weather source. Essential for all businesses with outdoor customers.',
  },
  {
    url: 'https://www.spc.noaa.gov/products/spcwwrss.xml',
    title: 'NOAA Storm Prediction Center — Watches & Warnings',
    description: 'Severe weather watches, tornado warnings, and storm prediction updates from NOAA.',
    siteUrl: 'https://www.spc.noaa.gov',
    industry: 'weather',
    sourceType: 'weather',
    sourceQuality: 'official',
    contentTags: ['alerts'],
    qualityScore: 10,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Critical severe weather alerts. Essential for any business in tornado alley.',
  },
  {
    url: 'https://www.severe-weather.eu/feed/',
    title: 'Severe Weather Europe',
    description: 'Severe weather forecasts, tropical storm tracking, and climate analysis.',
    siteUrl: 'https://www.severe-weather.eu',
    industry: 'weather',
    sourceType: 'weather',
    sourceQuality: 'trusted',
    contentTags: ['alerts', 'news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Global severe weather focus. Supplements NOAA feeds with analysis.',
  },

  // ═══════════════════════════════════════════════════════════════
  // SPORTS (general + niche)
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.espn.com/espn/rss/news',
    title: 'ESPN — Top Headlines',
    description: 'Breaking sports news, scores, highlights, and commentary across all sports.',
    siteUrl: 'https://www.espn.com',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Primary sports news source. Great for "This week in sports" posts.',
  },
  {
    url: 'https://www.espn.com/espn/rss/nfl/news',
    title: 'ESPN — NFL',
    description: 'NFL news, scores, standings, and analysis.',
    siteUrl: 'https://www.espn.com/nfl',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'NFL-specific coverage. Highly seasonal — peak fall/winter engagement.',
  },
  {
    url: 'https://www.espn.com/espn/rss/nba/news',
    title: 'ESPN — NBA',
    description: 'NBA news, scores, standings, and analysis.',
    siteUrl: 'https://www.espn.com/nba',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'NBA-specific coverage.',
  },
  {
    url: 'https://www.espn.com/espn/rss/mlb/news',
    title: 'ESPN — MLB',
    description: 'MLB news, scores, standings, and analysis.',
    siteUrl: 'https://www.espn.com/mlb',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'MLB-specific coverage. Spring through fall.',
  },
  {
    url: 'https://www.espn.com/espn/rss/nhl/news',
    title: 'ESPN — NHL',
    description: 'NHL news, scores, standings, and analysis.',
    siteUrl: 'https://www.espn.com/nhl',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'NHL-specific coverage.',
  },
  {
    url: 'https://www.espn.com/espn/rss/ncf/news',
    title: 'ESPN — College Football',
    description: 'College football news, scores, rankings, and analysis.',
    siteUrl: 'https://www.espn.com/college-football',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'College football coverage. Extremely popular in the South and Midwest.',
  },
  {
    url: 'https://www.espn.com/espn/rss/ncb/news',
    title: 'ESPN — College Basketball',
    description: 'College basketball news, March Madness, scores, and analysis.',
    siteUrl: 'https://www.espn.com/mens-college-basketball',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'College basketball coverage. March Madness drives massive engagement.',
  },
  {
    url: 'https://www.espn.com/espn/rss/rpm/news',
    title: 'ESPN — Racing (NASCAR, F1)',
    description: 'NASCAR, Formula 1, and motorsports news, results, and analysis.',
    siteUrl: 'https://www.espn.com/racing',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Motorsports coverage. Strong in Southern and rural markets.',
  },
  {
    url: 'https://www.espn.com/espn/rss/golf/news',
    title: 'ESPN — Golf',
    description: 'PGA Tour, golf news, tournament results, and analysis.',
    siteUrl: 'https://www.espn.com/golf',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Golf coverage. Good for upscale and resort businesses.',
  },
  {
    url: 'https://www.espn.com/espn/rss/mma/news',
    title: 'ESPN — MMA/UFC',
    description: 'UFC, MMA news, fight results, rankings, and analysis.',
    siteUrl: 'https://www.espn.com/mma',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'MMA/UFC coverage. Growing audience, especially 18-34 demographic.',
  },
  {
    url: 'https://www.espn.com/espn/rss/soccer/news',
    title: 'ESPN — Soccer',
    description: 'MLS, Premier League, and international soccer news and analysis.',
    siteUrl: 'https://www.espn.com/soccer',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Soccer coverage. Growing U.S. audience, especially urban markets.',
  },
  {
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml',
    title: 'The New York Times — Sports',
    description: 'NYT sports journalism covering major leagues, Olympics, and sports culture.',
    siteUrl: 'https://www.nytimes.com/section/sports',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Premium sports journalism with in-depth features.',
  },
  {
    url: 'https://sports.yahoo.com/rss/',
    title: 'Yahoo Sports',
    description: 'Sports news, scores, fantasy sports, and analysis across all major leagues.',
    siteUrl: 'https://sports.yahoo.com',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Broad sports coverage with strong fantasy sports content.',
  },
  {
    url: 'https://www.cbssports.com/rss/headlines/',
    title: 'CBS Sports',
    description: 'CBS Sports headlines covering NFL, NBA, MLB, NHL, and college sports.',
    siteUrl: 'https://www.cbssports.com',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Major network sports coverage.',
  },
  {
    url: 'https://www.outsideonline.com/feed/',
    title: 'Outside Magazine',
    description: 'Outdoor adventure, fitness, gear reviews, and active lifestyle content.',
    siteUrl: 'https://www.outsideonline.com',
    industry: 'sports',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Outdoor sports and adventure. Great for outfitters and outdoor retailers.',
  },

  // ═══════════════════════════════════════════════════════════════
  // HOME SERVICES (HVAC, plumbing, electrical, DIY)
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://www.familyhandyman.com/feed/',
    title: 'Family Handyman',
    description: 'DIY home improvement tips, repair guides, and project ideas for homeowners.',
    siteUrl: 'https://www.familyhandyman.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Premier DIY publication. Perfect for HVAC, plumbing, and electrical businesses.',
  },
  {
    url: 'https://www.bobvila.com/feed',
    title: 'Bob Vila',
    description: 'Home improvement advice, DIY tutorials, and expert tips for homeowners.',
    siteUrl: 'https://www.bobvila.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Iconic home improvement brand. Trusted DIY authority.',
  },
  {
    url: 'https://www.houselogic.com/feed/',
    title: 'HouseLogic (NAR)',
    description: 'Home maintenance tips, improvement ideas, and homeownership advice from the National Association of Realtors.',
    siteUrl: 'https://www.houselogic.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'official',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'NAR-backed home maintenance resource. Highly credible.',
  },
  {
    url: 'https://blog.constellation.com/feed/',
    title: 'Constellation Energy Blog',
    description: 'Energy saving tips, home efficiency guides, and sustainability advice.',
    siteUrl: 'https://blog.constellation.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'how-to', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Energy efficiency content. Great for HVAC and electrical businesses.',
  },
  {
    url: 'https://www.remodelista.com/feed/',
    title: 'Remodelista',
    description: 'Home design, renovation inspiration, and curated product guides.',
    siteUrl: 'https://www.remodelista.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'did-you-know', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Design-focused home renovation. Great for contractors and remodelers.',
  },
  {
    url: 'https://www.hunker.com/feed',
    title: 'Hunker',
    description: 'Home design, DIY projects, and practical home improvement guides.',
    siteUrl: 'https://www.hunker.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Accessible home improvement content. Good for general contractors.',
  },
  {
    url: 'https://structuretech.com/feed/',
    title: 'Structure Tech Home Inspections Blog',
    description: 'Home inspection tips, maintenance checklists, and common house problems explained.',
    siteUrl: 'https://structuretech.com',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['tips', 'alerts', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Home inspection expertise. Perfect for plumbers, electricians, and HVAC pros.',
  },
  {
    url: 'https://diydoctor.org.uk/feed/',
    title: 'DIY Doctor',
    description: 'Step-by-step DIY tutorials, home repair guides, and project calculators.',
    siteUrl: 'https://www.diydoctor.org.uk',
    industry: 'home_services',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['how-to', 'tips'],
    qualityScore: 6,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'UK-based but universal DIY content. Good supplemental feed.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CYBERSECURITY
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://feeds.feedburner.com/TheHackersNews',
    title: 'The Hacker News',
    description: 'Leading cybersecurity news covering hacking, data breaches, vulnerabilities, and privacy.',
    siteUrl: 'https://thehackernews.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'did-you-know'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Top cybersecurity news source. Great for "Alert" and "Did you know?" posts.',
  },
  {
    url: 'https://krebsonsecurity.com/feed/',
    title: 'Krebs on Security',
    description: 'Investigative cybersecurity journalism covering cybercrime and computer security.',
    siteUrl: 'https://krebsonsecurity.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'did-you-know'],
    qualityScore: 10,
    localizable: true,
    updateFrequency: 'weekly',
    notes: 'Gold standard for cybersecurity investigation. Brian Krebs is the authority.',
  },
  {
    url: 'https://www.darkreading.com/rss.xml',
    title: 'Dark Reading',
    description: 'Enterprise security news covering attacks, breaches, vulnerabilities, and protection strategies.',
    siteUrl: 'https://www.darkreading.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'tips'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Leading enterprise security publication.',
  },
  {
    url: 'https://www.bleepingcomputer.com/feed/',
    title: 'BleepingComputer',
    description: 'Technology and security news to help users stay informed and protected online.',
    siteUrl: 'https://www.bleepingcomputer.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'how-to'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Malware and security focus with great how-to content for staying safe.',
  },
  {
    url: 'https://www.schneier.com/feed/atom/',
    title: 'Schneier on Security',
    description: 'Security analysis and commentary from renowned cryptographer Bruce Schneier.',
    siteUrl: 'https://www.schneier.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['did-you-know', 'news'],
    qualityScore: 9,
    localizable: false,
    updateFrequency: 'weekly',
    notes: 'Thought leadership in security. Excellent for educational posts.',
  },
  {
    url: 'https://www.helpnetsecurity.com/feed/',
    title: 'Help Net Security',
    description: 'Enterprise information security news, features, expert insights, and product reviews.',
    siteUrl: 'https://www.helpnetsecurity.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'alerts'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Comprehensive enterprise security coverage.',
  },
  {
    url: 'https://www.csoonline.com/feed/',
    title: 'CSO Online',
    description: 'Information and best practices for business continuity, data protection, and security.',
    siteUrl: 'https://www.csoonline.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'tips', 'how-to'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Business-focused security coverage. Great for B2B cybersecurity firms.',
  },
  {
    url: 'https://www.securityweek.com/feed/',
    title: 'SecurityWeek',
    description: 'Cybersecurity news, analysis, and insight for security professionals.',
    siteUrl: 'https://www.securityweek.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Professional security news and analysis.',
  },
  {
    url: 'https://www.cyberscoop.com/feed/',
    title: 'CyberScoop',
    description: 'Breaking cybersecurity news covering government, defense, and private sector security.',
    siteUrl: 'https://www.cyberscoop.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts'],
    qualityScore: 8,
    localizable: false,
    updateFrequency: 'multiple_daily',
    notes: 'Government and defense cybersecurity focus.',
  },
  {
    url: 'https://cybersecuritydive.com/feeds/news/',
    title: 'Cybersecurity Dive',
    description: 'In-depth cybersecurity journalism covering news and trends shaping the industry.',
    siteUrl: 'https://www.cybersecuritydive.com',
    industry: 'cybersecurity',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Part of Industry Dive network. Well-researched security news.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL / CONSUMER TRENDS
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://retaildive.com/feeds/news/',
    title: 'Retail Dive',
    description: 'In-depth journalism on news and trends shaping the retail industry.',
    siteUrl: 'https://www.retaildive.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 9,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Leading retail industry publication. Great for any retailer.',
  },
  {
    url: 'https://www.retailwire.com/feed/',
    title: 'RetailWire',
    description: 'Retail industry news analysis and discussion for professionals.',
    siteUrl: 'https://www.retailwire.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Retail professional community and analysis.',
  },
  {
    url: 'https://grocerydive.com/feeds/news/',
    title: 'Grocery Dive',
    description: 'News and trends in grocery retailing, online disruption, and changing consumer habits.',
    siteUrl: 'https://www.grocerydive.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Grocery-specific retail trends. Good for food retailers and suppliers.',
  },
  {
    url: 'https://www.cnbc.com/id/10000116/device/rss/rss.html',
    title: 'CNBC — Top News',
    description: 'Business and financial news covering markets, economy, and consumer trends.',
    siteUrl: 'https://www.cnbc.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 8,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Major business news. Covers consumer spending trends and retail earnings.',
  },
  {
    url: 'https://www.marketwatch.com/rss/topstories',
    title: 'MarketWatch',
    description: 'Financial news, stock market data, and analysis of economic and consumer trends.',
    siteUrl: 'https://www.marketwatch.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Financial and consumer trend coverage. Good for business-facing retailers.',
  },
  {
    url: 'https://www.pymnts.com/feed/',
    title: 'PYMNTS',
    description: 'News and analysis on payments, commerce, and the connected economy.',
    siteUrl: 'https://www.pymnts.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'tips'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'multiple_daily',
    notes: 'Payments and commerce trends. Good for retail tech and POS businesses.',
  },
  {
    url: 'https://www.supplychaindive.com/feeds/news/',
    title: 'Supply Chain Dive',
    description: 'Supply chain industry news covering logistics, procurement, and operations.',
    siteUrl: 'https://www.supplychaindive.com',
    industry: 'retail_consumer',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'alerts', 'did-you-know'],
    qualityScore: 7,
    localizable: true,
    updateFrequency: 'daily',
    notes: 'Supply chain focus. Relevant for retailers dealing with logistics.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CROSS-INDUSTRY BONUS (tech + business overlap)
  // ═══════════════════════════════════════════════════════════════
  {
    url: 'https://techcrunch.com/feed/',
    title: 'TechCrunch',
    description: 'Startup news, technology trends, product launches, and venture capital coverage.',
    siteUrl: 'https://techcrunch.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know'],
    qualityScore: 9,
    localizable: false,
    updateFrequency: 'multiple_daily',
    notes: 'Premier startup/tech news. Also relevant for small_business.',
  },
  {
    url: 'https://www.wired.com/feed/rss',
    title: 'WIRED',
    description: 'In-depth reporting on technology, science, security, and innovation.',
    siteUrl: 'https://www.wired.com',
    industry: 'technology',
    sourceType: 'national_news',
    sourceQuality: 'trusted',
    contentTags: ['news', 'did-you-know', 'how-to'],
    qualityScore: 9,
    localizable: false,
    updateFrequency: 'multiple_daily',
    notes: 'Premium tech journalism. Also covers cybersecurity and culture.',
  },
];

// ═══════════════════════════════════════════════════════════════════
// SEED EXECUTION
// ═══════════════════════════════════════════════════════════════════

async function main() {
  console.log(`\n🌐 National RSS Feed Discovery — Seeding ${NATIONAL_FEEDS.length} feeds...\n`);

  const industries: Record<string, number> = {};
  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const feed of NATIONAL_FEEDS) {
    try {
      const existing = await prisma.rssFeed.findUnique({ where: { url: feed.url } });

      if (existing) {
        await prisma.rssFeed.update({
          where: { url: feed.url },
          data: {
            title: feed.title,
            description: feed.description,
            siteUrl: feed.siteUrl,
            industry: feed.industry,
            sourceType: feed.sourceType,
            sourceQuality: feed.sourceQuality,
            contentTags: feed.contentTags,
            qualityScore: feed.qualityScore,
            localizable: feed.localizable,
            updateFrequency: feed.updateFrequency,
            geoScope: 'national',
            status: 'active',
            discoveredBy: 'curated',
            discoveryMethod: 'curated',
            notes: feed.notes,
          },
        });
        updated++;
      } else {
        await prisma.rssFeed.create({
          data: {
            url: feed.url,
            title: feed.title,
            description: feed.description,
            siteUrl: feed.siteUrl,
            language: 'en',
            industry: feed.industry,
            sourceType: feed.sourceType,
            sourceQuality: feed.sourceQuality,
            contentTags: feed.contentTags,
            qualityScore: feed.qualityScore,
            localizable: feed.localizable,
            updateFrequency: feed.updateFrequency,
            geoScope: 'national',
            status: 'active',
            discoveredBy: 'curated',
            discoveryMethod: 'curated',
            notes: feed.notes,
          },
        });
        created++;
      }

      industries[feed.industry] = (industries[feed.industry] || 0) + 1;
    } catch (err: any) {
      console.error(`  ❌ Error seeding ${feed.url}: ${err.message}`);
      errors++;
    }
  }

  console.log('\n📊 Summary by Industry:');
  Object.entries(industries)
    .sort((a, b) => b[1] - a[1])
    .forEach(([industry, count]) => {
      console.log(`  ${industry.padEnd(20)} ${count} feeds`);
    });

  console.log(`\n✅ Created: ${created}`);
  console.log(`🔄 Updated: ${updated}`);
  if (errors > 0) console.log(`❌ Errors:  ${errors}`);
  console.log(`📦 Total:   ${NATIONAL_FEEDS.length} feeds across ${Object.keys(industries).length} industries\n`);
}

main()
  .catch((e) => {
    console.error('Fatal error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });