/**
 * Milestone 10 — redirect plan generator + static redirect-file emitter (pure).
 *
 * Turns a set of preservation mappings into:
 *   1. website_redirect_plan.json  (durable, auditable artifact)
 *   2. a `_redirects` file body     (Cloudflare Pages / static-export format)
 *   3. per-sitemap-page backlinkPreservation metadata
 *
 * NEVER deploys, publishes, or mutates DNS/hosting. Emitting a `_redirects`
 * FILE into the portable package is not a deployment — it is an artifact the
 * (separately-gated) future deploy step would consume.
 */

import type {
  BacklinkPriority,
  PreservationAction,
  PreservationMapping,
  SitemapPageBacklinkPreservation,
  WebsiteRedirectPlan,
} from '@/lib/site-backlinks/types';
import { isHighValue, priorityRank } from '@/lib/site-backlinks/priority';

export interface BuildRedirectPlanArgs {
  businessId: string;
  websiteProjectId?: string | null;
  sitemapId?: string | null;
  inventoryId?: string | null;
  mappings: PreservationMapping[];
  /** Approved mapping ids/paths (from oldPath) — approved redirects only. */
  approvedPaths?: Set<string>;
  status?: WebsiteRedirectPlan['status'];
}

export function buildRedirectPlan(args: BuildRedirectPlanArgs): WebsiteRedirectPlan {
  const approved = args.approvedPaths || new Set<string>();
  const redirects: WebsiteRedirectPlan['redirects'] = [];
  const preservedUrls: WebsiteRedirectPlan['preservedUrls'] = [];
  const ignoredUrls: WebsiteRedirectPlan['ignoredUrls'] = [];
  const unmappedUrls: WebsiteRedirectPlan['unmappedUrls'] = [];

  for (const m of args.mappings) {
    switch (m.action) {
      case 'preserve_same_url':
        preservedUrls.push({ path: m.oldPath, reason: m.reason });
        break;
      case 'redirect_301':
        if (m.newPath) {
          redirects.push({
            from: m.oldPath,
            to: m.newPath,
            statusCode: 301,
            reason: m.reason,
            priority: m.priority,
            approved: approved.has(m.oldPath),
          });
        } else {
          unmappedUrls.push({ path: m.oldPath, priority: m.priority, backlinkCount: m.backlinkCount });
        }
        break;
      case 'ignore_no_value':
        ignoredUrls.push({ path: m.oldPath, reason: m.reason, priority: m.priority });
        break;
      case 'rebuild_page':
        // A rebuild keeps the same path → treat as preserved-in-place.
        preservedUrls.push({ path: m.oldPath, reason: m.reason });
        break;
      case 'needs_review':
      default:
        unmappedUrls.push({ path: m.oldPath, priority: m.priority, backlinkCount: m.backlinkCount });
        break;
    }
  }

  const summary = {
    totalBacklinkUrls: args.mappings.length,
    preserved: preservedUrls.length,
    redirected: redirects.length,
    ignored: ignoredUrls.length,
    unmapped: unmappedUrls.length,
  };

  return {
    businessId: args.businessId,
    websiteProjectId: args.websiteProjectId || null,
    sitemapId: args.sitemapId || null,
    inventoryId: args.inventoryId || null,
    status: args.status || 'draft',
    redirects,
    preservedUrls,
    ignoredUrls,
    unmappedUrls,
    summary,
  };
}

/**
 * Emit a Cloudflare-Pages / static `_redirects` body from a redirect plan.
 * Only 301 rows are emitted. One rule per line: `<from> <to> 301`.
 */
export function emitRedirectsFile(plan: WebsiteRedirectPlan): string {
  const lines: string[] = [
    '# Generated by Launch OS backlink-preservation layer (Milestone 10).',
    '# 301 redirects preserve SEO equity from the previous site. NOT auto-deployed.',
  ];
  for (const r of plan.redirects) {
    lines.push(`${r.from} ${r.to} 301`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Compute the set of high-value old URLs that are NOT safely preserved yet
 * (unmapped or needs_review). These block deployment readiness.
 */
export function unmappedHighValue(mappings: PreservationMapping[]): PreservationMapping[] {
  return mappings.filter(
    (m) =>
      isHighValue(m.priority) &&
      (m.action === 'needs_review' ||
        (m.action === 'redirect_301' && !m.newPath) ||
        m.status === 'needs_review'),
  );
}

/** Medium-value URLs that still need review (warn, not block). */
export function needsReviewMedium(mappings: PreservationMapping[]): PreservationMapping[] {
  return mappings.filter(
    (m) => m.priority === 'medium' && (m.action === 'needs_review' || m.status === 'needs_review'),
  );
}

/**
 * Attach per-page backlinkPreservation metadata to sitemap pages, keyed by the
 * page's normalized path. Returns a Map<newPath, meta> the caller can merge into
 * each SitemapPage.
 */
export function buildPagePreservationMap(
  mappings: PreservationMapping[],
): Map<string, SitemapPageBacklinkPreservation> {
  const byNewPath = new Map<string, SitemapPageBacklinkPreservation>();
  const add = (
    path: string,
    oldUrl: string,
    priority: BacklinkPriority,
    action: PreservationAction,
    redirectTarget: string | null,
    needsReview: boolean,
    reason: string,
  ) => {
    const cur = byNewPath.get(path);
    if (!cur) {
      byNewPath.set(path, {
        oldUrls: [oldUrl],
        backlinkPriority: priority,
        preservationAction: action,
        redirectTarget,
        needsReview,
        reason,
      });
      return;
    }
    cur.oldUrls.push(oldUrl);
    if (priorityRank(priority) > priorityRank(cur.backlinkPriority || 'low')) {
      cur.backlinkPriority = priority;
    }
    cur.needsReview = cur.needsReview || needsReview;
  };

  for (const m of mappings) {
    const needsReview = m.action === 'needs_review' || m.status === 'needs_review';
    if (m.action === 'preserve_same_url' || m.action === 'rebuild_page') {
      if (m.newPath || m.oldPath) add(m.newPath || m.oldPath, m.oldPath, m.priority, m.action, null, needsReview, m.reason);
    } else if (m.action === 'redirect_301' && m.newPath) {
      add(m.newPath, m.oldPath, m.priority, m.action, m.oldPath, needsReview, m.reason);
    }
    // ignore_no_value + unmapped needs_review are NOT attached to a page.
  }
  return byNewPath;
}
